name: Build

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-20.04
    strategy:
      max-parallel: 4
      matrix:
        python-version: ['3.7', '3.8', '3.9', '3.10']

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Setup Compiler
      run: |
        sudo apt-get -y install gcc gfortran
    - name: Setup LibClang
      run: |
        sudo apt-get -y install libclang-dev python-clang
        SP=~/.local/lib/python${{ matrix.python-version }}/site-packages
        mkdir -p $SP
        cp -vr /usr/lib/python3/dist-packages/clang $SP/
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
    - name: Type check with mypy
      run: |
        pip install -e .[dev]
        pip install pytest
        python -m mypy setup.py source tests/unit_tests
    - name: Code style check with flake8
      run: |
        pip install -e .[dev]
        flake8 . --count --show-source --statistics
    - name: Unit tests with Pytest
      run: |
        pip install .[tests]
        python -m pytest --cov=fab tests/unit_tests
    - name: Integration tests with Pytest
      run: |
        pip install .[tests]
        python -m pytest --cov=fab tests/integration_tests
    - name: System tests with Pytest
      run: |
        pip install .[tests]
        python -m pytest --cov=fab --ignore=run-configs system-tests-new
